# Generated by Django 5.0.1 on 2024-02-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='breed',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='age',
            new_name='year',
        ),
    ]
