# Generated by Django 5.0.1 on 2024-02-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_bands_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='band',
            field=models.ManyToManyField(to='main_app.band'),
        ),
    ]
